# Travis configuration for C project by Javier Balloffet

language: c

compiler: gcc

script:
  - make
  - make test
  - make coverage

after_success:
  - echo "Success! :)"
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "Failure... :("
