# Travis configuration for C template project
# Author: Javier Balloffet <javier.balloffet@gmail.com>

os: linux
dist: bionic
language: c
compiler: gcc

addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - valgrind

script:
  # Build app
  - make
  # Build and run unit tests
  - make test
  # Build and check documentation
  - make doc
  - bash scripts/check_doc.sh
  # Check coding style
  - make format
  - bash scripts/check_format.sh
  # Static analysis check
  - make tidy > tidy_log.txt
  - bash scripts/check_tidy.sh
  # Dynamic analysis check
  - make memcheck

after_success:
  - echo "Success! :)"
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "Failure... :("
