# Travis configuration for C Project Template
# Author: Javier Balloffet <javier.balloffet@gmail.com>

os: linux
dist: bionic
language: c
compiler: gcc

stages:
  - build
  - test
  - report

addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - valgrind

jobs:
  include:
    # Build application
    - name: "build-app"
      stage: build
      script:
        - make
    # Build and check documentation
    - name: "build-doc"
      stage: build
      script:
        - make doc
        - bash scripts/check_doc.sh
    # Build and run unit tests
    - name: "run-unit-tests"
      stage: test
      script:
        - make test
    # Coding style analysis
    - name: "run-coding-style-analysis"
      stage: test
      script:
        - make format
        - bash scripts/check_format.sh
    # Static analysis
    - name: "run-static-analysis"
      stage: test
      script:
        - make tidy > tidy_log.txt
        - bash scripts/check_tidy.sh
    # Dynamic analysis
    - name: "run-dynamic-analysis"
      stage: test
      script:
        - make memcheck
    # Run Google's Address and Leak Sanitizer (ASAN and LSAN)
    - name: "run-google-asan"
      stage: test
      script:
        - make test COMPILER=clang DEBUG=on GOOGLE_SANITIZER=asan
    # Run Google's Memory Sanitizer (MSAN)
    - name: "run-google-msan"
      stage: test
      script:
        - make test COMPILER=clang DEBUG=on GOOGLE_SANITIZER=msan
    # Run Google's Undefined Behavior Sanitizer (UBSAN)
    - name: "run-google-ubsan"
      stage: test
      script:
        - make test COMPILER=clang DEBUG=on GOOGLE_SANITIZER=ubsan
    # Compute code coverage
    - name: "compute-code-coverage"
      stage: report
      script:
        - make test DEBUG=on COVERAGE=on
      after_success:
        - bash <(curl -s https://codecov.io/bash)
