# Travis configuration for C template project
# Author: Javier Balloffet <javier.balloffet@gmail.com>

os: linux
dist: bionic
language: c
compiler: gcc

addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - valgrind

script:
  # Build app
  - make
  # Build and run unit tests
  - make test
  # Build and check documentation
  - make doc
  - |
    if [[ -s doc/doxygen_warning_log.txt ]]; then
      echo "Please fix doxygen warnings:"
      cat doc/doxygen_warning_log.txt
      exit -1
    fi
  # Check coding style
  - make format
  - |
    if [[ -n $(git diff) ]]; then
      echo "Please run make format"
      exit -1
    fi
  # Static analysis check
  # - make tidy > results.txt
  # - |
  #   if [[ -n $(grep "warning: " results.txt) ]] || [[ -n $(grep "error: " results.txt) ]]; then
  #     echo "Please fix ClangTidy warnings and/or errors:"
  #     grep --color -E '^|warning: |error: ' results.txt
  #     exit -1;
  #   fi
  # Dynamic analysis check
  - make memcheck

after_success:
  - echo "Success! :)"
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "Failure... :("
