# Travis configuration for C project by Javier Balloffet

language: c

compiler: gcc

script:
  # Build app
  - make
  # Build and run unit tests
  - make test
  # Build and check documentation
  - make doc
  - |
    if [[ -s doc/doxygen_warning_log.txt ]]; then
      echo "Please fix doxygen warnings:"
      cat doc/doxygen_warning_log.txt
      exit -1
    fi

after_success:
  - echo "Success! :)"
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "Failure... :("
